apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: data-mover
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: data-mover
spec:
  selector:
    matchLabels:
      control-plane: data-mover
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: data-mover
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        image: controller:latest
        imagePullPolicy: Always
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
