# permissions for end users to edit dataimports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataimport-editor-role
rules:
- apiGroups:
  - ys.jibudata.com
  resources:
  - dataimports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - dataimports/status
  verbs:
  - get
