# permissions for end users to view dataexports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataexport-viewer-role
rules:
- apiGroups:
  - ys.jibudata.com
  resources:
  - dataexports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - dataexports/status
  verbs:
  - get
