# permissions for end users to view dataimports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataimport-viewer-role
rules:
- apiGroups:
  - ys.jibudata.com
  resources:
  - dataimports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - dataimports/status
  verbs:
  - get
