
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - velero.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - veleroexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - veleroexports/finalizers
  verbs:
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - veleroexports/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - veleroimports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - veleroimports/finalizers
  verbs:
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - veleroimports/status
  verbs:
  - get
  - patch
  - update
