
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ys.jibudata.com
  resources:
  - dataexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - dataexports/finalizers
  verbs:
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - dataexports/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - dataimports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - dataimports/finalizers
  verbs:
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - dataimports/status
  verbs:
  - get
  - patch
  - update
