# permissions for end users to view veleroexports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: veleroexport-viewer-role
rules:
- apiGroups:
  - ys.jibudata.com
  resources:
  - veleroexports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - veleroexports/status
  verbs:
  - get
