# permissions for end users to edit veleroexports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: veleroexport-editor-role
rules:
- apiGroups:
  - ys.jibudata.com
  resources:
  - veleroexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - veleroexports/status
  verbs:
  - get
