# permissions for end users to view veleroimports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: veleroimport-viewer-role
rules:
- apiGroups:
  - ys.jibudata.com
  resources:
  - veleroimports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - veleroimports/status
  verbs:
  - get
